### ISSUE TITLE
Can't download unprocessed version of image in edit mode

### ISSUE THREAD

**Issue by tanemann** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#10]
If you download an image file in the Media gadget (via the context menu) you always end up with a processed version of the file. This is especially problematic when using the PdfiumRenderer plugin, because you get a JPG-rendered version of the PDF file, instead of the PDF file itself.

The reason why this happens is that in OnPostAuthorizeRequestStart you modify the request URL by removing everything after the first comma. The download URL looks like **/episerver/CMS/Content/globalassets/file.pdf,,97535/Download?epieditmode=False**. So you end up with 
**/episerver/CMS/Content/globalassets/file.pdf** and since you also have _"process", ProcessWhen.Always.ToString()_, the file is processed even though there is no ImageResizer query parameters in the URL (why would you force processing anyway?).

This leads to a bigger question: what's the point of the whole OnPostAuthorizeRequestStart method? It's relatively slow, because it uses UrlResolver.Route() and it's not supposed to be slow, since it's called for every single request. As far as I can tell, the method is used so that cached images are not served in the edit mode. But that would not be a problem if you didn't strip everything after the comma in the URL, since Episerver adds the content work ID in the URL anyway, e.g.:
**/episerver/CMS/Content/globalassets/file.pdf,,97535_262312?epieditmode=False**
**/episerver/CMS/Content/globalassets/file.pdf,,97535_262312?/Thumbnail?epieditmode=False?1463982947728**
So if the content changes, the URL changes and caching shouldn't be a problem.

I've tried using the BlobReader plugin without the OnPostAuthorizeRequestStart, and so far I haven't noticed any problems with it. So unless there's a good reason for the method, it should be removed, as it already has bugs in it and is error-prone due to magic literals like "Thumbnail?epieditmode".

**Comment by valdisiljuconoks** [comment]
Hi,

Thanks for great explanation on the issue. As currently I'm just author of the package, I do not know the code so well. Think I need to transfer ownership and take a closer look.

Will keep updated..

**Comment by valdisiljuconoks** [comment]
This is fixed in v4.0.3

**Comment by valdisiljuconoks** [comment]
If not working, please - reopen

**Comment by valdisiljuconoks** [comment]
However, there is one downside to this case.
Image that you are using Image Resizer (IR) for render some image on the page and you are adding IR specific url attributes to do the post-processing (resizing for instance).

When you are in edit mode, IR will not kick it and you might see unprocessed (might be original dimensions of the image) in CMS edit mode - which in this case will probably break layout of the page.

So decision was made to skip post-processing if on Edit mode - and have this downside. So - if you are doing IR magic on the images on the site, you will need to handle Url generation yourself. And using `@Url.ContentUrl(...)` will give you context aware links (with ,, and other magic).

One of the easiest solution is to pass in context mode while rendering image Url (this of course might me converted to extension method or something in your projects):

```
<img src="@UrlResolver.Current.GetUrl(new UrlBuilder(...), ContextMode.Default)?w=.."/>
```

**Comment by shinpou** [comment]
I want to futher elaborate what was said in the previous post for anyone being hit by the issue above and you're questioning if this change was necessary.

It is my understanding after reviewing this change, that it is a problem specifically in ImageResizer itself, that it does not kick in for URLs that have commas and some other special characters in them. In Episerver edit mode, Episerver adds weird characters to image urls to somehow make it possible to roundtrip contentlinks in image urls. To make it work for edit mode, the url had to be modified in flight (before IR gets it) to something IR would grab on to.

This to me justifies this change, because fixing the problem should occur at the level where the bug is, so in ImageResizer. Also, creating image urls via contextmode as shown above is considerably cleaner than having a hack inside the imageresizer plugin which also might have performance issues.

**Comment by tanemann** [comment]
Hi, I finally returned to work from a long vacation and had some time to look at this again. It seems that removing the URL handling in OnPostAuthorizeRequestStart does indeed break image scaling in Edit mode, which is a pretty critical breaking change. Using ContextMode.Default when rendering image URLs does fix the issue, but it's pretty troublesome and error prone having to use it everywhere, so I'd prefer some other way of dealing with Edit mode URLs. 

As @shinpou said, the problem seems to be caused by the fact that if there are commas in a URL, IR skips it completely. However, it doesn't seem to be an issue in IR itself, since a static file with commas in its name (e.g. /file,,123.jpg), is handled just fine by IR. So it seems that it's in fact Episerver itself that somehow messes with routing when there are commas present in the URL.

I've come up with this code that works fine when using normal URLs, Edit mode URLs and thumbnail URLs:

```
        private static void OnPostAuthorizeRequestStart(IHttpModule sender, HttpContext context)
        {
            // A hack to get ImageResizer working with images in edit mode.
            // In edit mode image URLs look like http://host.com/ui/CMS/Content/contentassets/0c51b2fa1f464956aab221c6ecc21804/file.jpg,,82777?epieditmode=False&width=100
            // For some reason, URLs that have commas in them aren't processed by ImageResizer, so they need to be removed from the end of the path.
            // Episerver can still route content even without the commas and the content ID.

            // Thumbnail URLs should not be modified, e.g. 
            // http://host.com/ui/CMS/Content/contentassets/0c51b2fa1f464956aab221c6ecc21804/file.jpg,,82777/Thumbnail?epieditmode=False?1470652477313

            var fixedUrl = PathRegex.Replace(context.Request.Url.AbsolutePath, string.Empty);
            Config.Current.Pipeline.PreRewritePath = fixedUrl;
        }

        private static readonly Regex PathRegex = new Regex(@",[^\/]*", RegexOptions.Compiled);
```

It's possible (even likely) that it will not work with every internal URL Episerver uses. But it should be better and faster than the original OnPostAuthorizeRequestStart implementation, and it doesn't break stuff in the Edit mode, like removing OnPostAuthorizeRequestStart completely does.

**Comment by valdisiljuconoks** [comment]
So you guys are considering that we should put it back?

**Comment by Souperman** [comment]
Hello!

Is there any progress with the above issue?

Not sure it's related but we saw the issue on a previous version (where the URL contained /Thumbnail you forced IR to not fire), this fix works fine for images in the "Assets" tab, however the main product image is actually /LargeThumbnail - so we get a 404 here.

**Comment by valdisiljuconoks** [comment]
Hi all,

Thanks for suggestion on fixing the url. Seems like this does not break edit mode.

http://nuget.episerver.com/en/OtherPages/Package/?packageId=ImageResizer.Plugins.EPiServerBlobReader&packageVersion=4.1.0

**Comment by valdisiljuconoks** [comment]
Souperman, are you referring to Commerce product?

**Comment by valdisiljuconoks** [comment]
Also added in sample website small helper. Looks neat :)

https://github.com/valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader/blob/master/samples/SampleAlloy/Business/Rendering/HtmlHelperExtensions.cs#L10

**Comment by Souperman** [comment]
Hi Valdis, yes - sorry for not specifying. The "main" product/variant image contains the "LargeThumbnail" in the URL, and I get a 404 error when viewing the image - the asset "thumbnail"s work fine though.

**Comment by valdisiljuconoks** [comment]
wait for 4.1 to come out and see if that fixes the issue. btw, which version are you using now?
