### ISSUE TITLE
Can't use custom template for images in edit mode

### ISSUE THREAD

**Issue by mukkol** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#11]
Hi,

I've noticed that custom templates won't get loaded on Episerver CMS (UI) version 9.6.2 when plugin is enabled. If I disable the plugin or uninstall it the custom templates are working just fine. Templates used to work with previous episerver (CMS 8) and plugin version (3.0.1).

For example following custom edit view for images does not work with Alloy demo if plugin is enabled.
I was just thinking if this could be related to issue https://github.com/valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader/issues/10?

[CustomPreviewTemplateForAlloyDemo.zip](https://github.com/valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader/files/304394/CustomPreviewTemplateForAlloyDemo.zip)

**Comment by valdisiljuconoks** [comment]
Will look into this together with issue #10. Thanks!

**Comment by valdisiljuconoks** [comment]
Can you verify that this is working with v4.0.3 ?

**Comment by mukkol** [comment]
Based on couple of quick test I'd say that it's working with v.4.0.3. Thanks a lot!
