### ISSUE TITLE
Images without extension

### ISSUE THREAD

**Issue by jonasboman** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#12]
ImageResizer does not kickin on images without extensions (jpg,png,gif...) in its name.
The type used is ImageFile which is derived from ImageData.
Are there any solution to this without making sure extension always exist?

**Comment by valdisiljuconoks** [comment]
Hi,

If you have time, you can experiment with adding check for extensionless cases. Some clues could be found here: http://imageresizing.net/docs/v4/howto/cache-non-images

**Comment by valdisiljuconoks** [comment]
Hi Jonas,

Any luck with this issue?

**Comment by jonasboman** [comment]
Hi. No, not yet. Vacation ☺️
Will get back to you after.

Den tis 26 juli 2016 14:32Valdis Iljuconoks <notifications@github.com>
skrev:

**Comment by jonasboman** [comment]
I've come this far
```
Config.Current.Pipeline.PostAuthorizeRequestStart += delegate (IHttpModule sender2, HttpContext context) {
                string path = Config.Current.Pipeline.PreRewritePath;
                if (!path.StartsWith(ImageResizer.Util.PathUtils.ResolveAppRelative("~/contentassets"), StringComparison.OrdinalIgnoreCase)) return;
                try
                {
                    if (!string.IsNullOrEmpty(Path.GetExtension(path)))
                    {
                        return;
                    }
                }
                catch
                {
                    return;
                }
                Config.Current.Pipeline.SkipFileTypeCheck = true; 
                Config.Current.Pipeline.ModifiedQueryString["cache"] = ImageResizer.ServerCacheMode.Default.ToString();
                
            };
```

However this changes nothing. I guess I have to take some action after last line of code?!
//Mr Noob

**Comment by valdisiljuconoks** [comment]
Ok, I'll try to look into this issue next week.

**Comment by valdisiljuconoks** [comment]
Sorry for not handling this case. Strong sh** storm... ;)

**Comment by valdisiljuconoks** [comment]
While driving just thought about extension less images. What's media definition in your EPiServer to support extension less media?

**Comment by valdisiljuconoks** [comment]
Jonas, what about ensuring that images *have* extensions?

http://world.episerver.com/blogs/stephan-lonntorp/dates/2016/11/ensuring-image-extension-for-content/

**Comment by jonasboman** [comment]
We've added extension, but due to legacy reasons the problem still exists. It's about 200 images without extension that editors manually have to change the name on. This resources exist under a pages "For This Page". 
I've kind of come to terms that it's hard to do this in a good way and the best solution is to edit the names manually
