### ISSUE TITLE
Images are broken for WebEditors

### ISSUE THREAD

**Issue by russellshome** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#18]
In EpiServer, when logged in as editor an uploaded image is broken in the following circumstances:
- In Media - Select Image - Edit
- Cannot drag/drop onto HTML editor
- When selecting the image in TinyMCE
- After selecting the image using Tiny MCE

**Comment by valdisiljuconoks** [comment]
Regarding media published requirement: there is a blog post http://blog.tech-fellow.net/2016/10/31/imageresizer-plugin-for-episerver-v10/.

Maybe should add readme file once package is installed  - so people will be aware of that..
