### ISSUE TITLE
nuget install does not set up all required config settings

### ISSUE THREAD

**Issue by russellshome** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#19]
Missing:

- system.WebServer - modules - &lt;add name="ImageResizingModule" type="ImageResizer.InterceptModule" />

- system.web - httpModules - &lt;add name="ImageResizingModule" type="ImageResizer.InterceptModule" />

**Comment by valdisiljuconoks** [comment]
Will add dependency to `ImageResizer.WebConfig` package
