### ISSUE TITLE
If image is null, throwing exception

### ISSUE THREAD

**Issue by LucGosso** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#20]
Hi Valdis,

**if Model.CurrentPage.Image is null**, it throws exception on page render, when page created in editmode
`@if (!ContentReference.IsNullOrEmpty(Model.CurrentPage.Image) || PageEditing.PageIsInEditMode)
{<div class="image" @Html.EditAttributes(m => m.CurrentPage.Image)><img src="@Html.ResizeImage(Model.CurrentPage.Image).Width(795).Height(530).FitMode(FitMode.Crop)" /></div>}`

Default behavior is normally with Url.ContentUrl(Model.CurrentPage.Image) returning empty string

**Workaround** 
`<img src="@Url.ContentUrl(Model.CurrentPage.Image)?width=795&height=530&mode=crop" />`

having PageEditing.PageIsInEditMode i want to show the property in editmode, to be able to change it. 

**Request**
Add fallback image property
`@Html.ResizeImage(Model.CurrentPage.MainImage, "/content/images/no-image-found.jpg").Width(795).Height(530).FitMode(FitMode.Crop)`

also nicer exception message saying something like "Image is null, please use the fallbackproperty"

Do you want me to contribute and send pull request?

**Comment by LucGosso** [comment]
oh crap, you have that ResizeImageWithFallback! =) 

okey, then another errormessage would have saved me some time here ;)

**Comment by valdisiljuconoks** [comment]
https://blog.tech-fellow.net/2017/06/05/breaking-changes-in-imageresizer-episerver-plugin/

**Comment by valdisiljuconoks** [comment]
look for v6.0.1 ;)
