### ISSUE TITLE
EPICommerce Catalog images broken

### ISSUE THREAD

**Issue by jeroenvanlieshout** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#23]
When using Episerver Commerce, the thumbnail product images are broken in edit mode of catalog entry:
![image](https://user-images.githubusercontent.com/13566988/37952912-ac13f6e6-31a1-11e8-82b7-8d459c5a328f.png)
This issue arises when installing the imageresizer component. Episerver Commerce OOTB uses a LargeThumbnail URL which breaks when using imageresizer. An example URL format which is used:
https://localhost/EPiServer/CMS/Content/siteassets/image.png,,492/LargeThumbnail?epieditmode=False&time=1522135887646
I think something needs to be changed in the URL filtering mechanism to not let handle imageresizer this functionality, but to fall back on OOTB epi functionality.

To reproduce easily: install quicksilver example, install ImageResizer.Plugins.EPiServerBlobReader package and check behavior in catalog.

**Comment by valdisiljuconoks** [comment]
which version of the package are you using?

**Comment by jeroenvanlieshout** [comment]
Image Resizer Packages:
ImageResizer 4.2.5
ImageResizer.Mvc 4.2.5
ImageResizer.MvcWebConfig 4.2.5
ImageResizer.Plugins.DiskCache 4.2.5
ImageResizer.WebConfig 4.2.5
ImageResizer.Plugins.EPiServerBlobReader 7.0.1

EPI Versions:
CMS: 11.5.4
Commerce: 12.1.0

**Comment by valdisiljuconoks** [comment]
Hi,

Sorry for `Task.Delay` here. I tested this scenario over the weekend and you know, it's weird, but I cannot repro this.

![image](https://user-images.githubusercontent.com/1767179/41205875-02421ca8-6d04-11e8-828f-8cfa2151c2c1.png)

```
<package id="EPiServer.CMS" version="11.5.3" targetFramework="net461" />
<package id="EPiServer.CMS.AspNet" version="11.5.3" targetFramework="net461" />
<package id="EPiServer.CMS.Core" version="11.5.3" targetFramework="net461" />
<package id="EPiServer.CMS.TinyMce" version="2.1.1" targetFramework="net461" />
<package id="EPiServer.CMS.UI" version="11.4.3" targetFramework="net461" />
<package id="EPiServer.CMS.UI.AspNetIdentity" version="11.4.3" targetFramework="net461" />
<package id="EPiServer.CMS.UI.Core" version="11.4.3" targetFramework="net461" />
<package id="EPiServer.Commerce" version="12.2.0" targetFramework="net461" />
<package id="EPiServer.Commerce.Core" version="12.2.0" targetFramework="net461" />
<package id="EPiServer.Commerce.UI" version="12.2.0" targetFramework="net461" />
<package id="EPiServer.Commerce.UI.CustomerService" version="12.2.0" targetFramework="net461" />
<package id="EPiServer.Commerce.UI.ManagerIntegration" version="12.2.0" targetFramework="net461" />
<package id="EPiServer.Framework" version="11.5.3" targetFramework="net461" />
<package id="EPiServer.Framework.AspNet" version="11.5.3" targetFramework="net461" />
<package id="EPiServer.Logging.Log4Net" version="2.2.2" targetFramework="net461" />
<package id="EPiServer.Personalization.Commerce" version="1.2.0" targetFramework="net461" />
<package id="EPiServer.Personalization.Common" version="1.1.0" targetFramework="net461" />
<package id="EPiServer.ServiceLocation.StructureMap" version="2.0.1" targetFramework="net461" />
<package id="EPiServer.Tracking.Commerce" version="1.2.0" targetFramework="net461" />
<package id="EPiServer.Tracking.Core" version="1.4.0" targetFramework="net461" />
<package id="ImageResizer" version="4.0.1" targetFramework="net461" />
<package id="ImageResizer.Plugins.EPiServerBlobReader" version="7.0.1" targetFramework="net461" />
<package id="ImageResizer.WebConfig" version="4.0.1" targetFramework="net461" />
```

**Comment by valdisiljuconoks** [comment]
however, I see that I did install all the packages you have..

**Comment by jeroenvanlieshout** [comment]
hmm, can't reproduce it from my end anymore in Quicksilver anymore. You may close it from my end. I will dig further into it what's causing the issue on our end. Thanks for the effort!
