### ISSUE TITLE
Why is format always image/png ?

### ISSUE THREAD

**Issue by bornemix** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#3]
(I realise that the following question might be more ImageResizer-specific, but sence this is the integration I use...)

Thanks for this great package. But my teaser versions et-al become huge png:s, even when the source file is jpeg.

Do you know anything?

**Comment by valdisiljuconoks** [comment]
I'll take a look. But I'm speculating that this is not package related as blob provider just delegates control further.

**Comment by bornemix** [comment]
Sure, but in that case maybe the package can supply parameters for
configuring it, if it's within the scope of the package?

Regards

2015-04-27 13:16 GMT+02:00 Valdis Iljuconoks <notifications@github.com>:

**Comment by valdisiljuconoks** [comment]
Hi,

Just tested on sample site. Requesting large jpeg file from the server through the plugin and eventually ImageResizer, response ContentType is set to "image/jpeg".

**Comment by bornemix** [comment]
Very strange (for me, that is)... thank you and sorry for taking your time!

2015-05-07 13:05 GMT+02:00 Valdis Iljuconoks <notifications@github.com>:
