### ISSUE TITLE
Rendered HTML doesn't validate

### ISSUE THREAD

**Issue by kledung** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#43]
The rendered HTML for the picture element doesn't validate (https://validator.w3.org) with the following error message:
Error: Stray end tag source.
</source>
Error: Stray end tag img.
</img>

Both the source and the img tags are self closing tags and should be closed as />.

**Comment by valdisiljuconoks** [comment]
Hi,

Thanks for pointing this out. Definitely should be fixed.
