### ISSUE TITLE
Version 2 requires .NET Framework 4.5.2

### ISSUE THREAD

**Issue by evest** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#6]
Are there any requirements in the module that prevents it from targeting 4.5? I know, kind of old, and EPiServer CMS 9 requires v4.5.2 according to the System Requirements.

However, it works with 4.5, and a lot of projects upgraded to CMS 9 have not been retargeted to 4.5.2. When they install the latest package, the assembly is not referenced. Since it is loaded by the ImageResizer plug-in system, it just fails silently when not found. The images just won't be resized anymore. Hard to troubleshoot (you'll see it in /resizer.debug if you know about it.)

**Comment by valdisiljuconoks** [comment]
No, it's not required to have 4.5.2. Will look into downgrading..

**Comment by evest** [comment]
My immediate need went away last night when I finally targeted 4.5.2 :-) But probably a good idea anyway.

**Comment by valdisiljuconoks** [comment]
Which ImageResizer version you are using? Considering to set reference to v4

**Comment by evest** [comment]
Using 3.4.2 right now. Didn't upgrade since there are license considerations I haven't had time to look into yet. But v4 looks good on paper.

This should probably bump this to v3 then, since it is a fairly large upgrade. Also, the plugin registration is more strict in web.config. It could break the site, and should require a readme. The MVC plugin is not required for v4, so it is a simpler set up.

v4.0.4 requires .NET 4.5.2 :-)

Most importantly, the license changes must be verified. If moving to v4 requires a paid license, or open sourcing the whole project, it must be a deliberate decision by the end user.
