### ISSUE TITLE
PdfRenderer doesn't work because regexes don't contain "pdf"

### ISSUE THREAD

**Issue by tanemann** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#7]
The PdfRenderer plugin doesn't work with EPiServerBlobReader. The regexes only include image file extensions, so the reader ignores PDF files. As the ToDos suggest, ideally the list of supported file extensions should not be hard-coded but would instead be acquired from the plugins that ImageResizer has loaded at the time. I think you can get those using ImageResizer.Configuration.Config.Current.Pipeline.AcceptedImageExtensions.

**Comment by valdisiljuconoks** [comment]
If using ImageResizer v4 - look for NuGet package version 4.0 on EPiServer feed.
If ImageResizer v3.x - look for NuGet package version 3.0.

Thanks!
